sparkfun/Arduino_Apollo3

cores/arduino/ard_sup/Arduino.h, cores/arduino/ard_sup/ap3_clock_sources.h, cores/arduino/ard_sup/clock/ap3_clock_sources.cpp, libraries/CoreTesting/examples/Advanced/BurstMode/BurstMode.ino
Allows users to run at 96MHz or 48MHz
I created two new functions called:
* enableBurstMode()
* disableBurstMode()
I welcome feedback if you want to do a different new-to-arduino naming convention.
=> Add enableBurstMode() function and example to core.

tools/artemis/artemis_svl.py
I had a sketch reporting 'No announcement from Artemis bootloader'. This occurs when either 1) no chr(127) is received or 2) too many non-chr(127) characters are received. The sketch I was working on transmits a ton of serial data at 115200 constantly. After the Artemis is reset, the python script has more than 10 bytes sitting in the buffer. 30 seems to work well. With a 0.1s timeout, this is 3s total. Increasing to 50 seems overkill.
=> Increasing wrong character timeout to 30 to fix 'no annoucement' error.

cores/arduino/ard_sup/analog/ap3_analog.cpp, cores/arduino/ard_sup/ap3_analog.h, cores/arduino/ard_sup/uart/ap3_uart.cpp
Basic helpers to Serial. Needed for low power operation. Also added an power_adc_disable() helper function. Not sure if this is the naming route we want to go. Similar to [AVR style](https://arduino.stackexchange.com/questions/50733/is-there-a-way-to-disable-modules-like-adc-without-a-sleep-mode).
=> Adds Serial.end(), .flush(), and power_adc_disable

cores/arduino/ard_sup/ap3_timing.h, cores/arduino/ard_sup/timing/ap3_timing.cpp
'seconds' is common enough it collides with example sketches. 'secs' follows the micros and millis convention (roughly).
=> Rename seconds() to secs() to avoid collisions with sketch variables

cores/arduino/am_sdk_ap3/mcu/apollo3/hal/am_hal_gpio.h, cores/arduino/ard_sup/Arduino.h, cores/arduino/ard_sup/ap3_shift.h, cores/arduino/ard_sup/gpio/ap3_shift.cpp, libraries/Examples/examples/Advanced/fastShift/fastShift.ino
Basic reference support for shiftIn/shiftOut as well as three new functions:
* enableFastShift() - Sets the proper bits in the am_hal_gpio_fast_pinconfig register
* fastShiftOut/fastShiftIn - Works on any GPIO
Using SPI hardware will always be better than fastGPIO but I wanted to make them available if wanted.
=> Add shiftIn/shiftOut as well as fastShiftIn/fastShiftOut

libraries/Examples/examples/Advanced/Artemis_Bootloader/Artemis_Bootloader.ino, tools/artemis/artemis_svl.py
This is meant to address platform discrepancies between Windows/MacOSX/Linux that caused failures with the bootloader. #21 and [Artemis Issue #2](https://github.com/sparkfun/SparkFun_Artemis/issues/2)
=> Artemis SparkFun Variable Loader (SVL) v2

tools/artemis/artemis_svl.py
Increases SVL speed by only checking available ports when the desired port cannot be opened. Also provides '-g' argument to SVL to override the default 50 ms global timeout (used for time out when negotiating baud rate)
=> SVL Speed Boost

docs/ACKNOWLEDGEMENTS.md
Added preliminary home page and software interrupts page to wiki, as a result of issue #34 in sparkfun/Ardunio_Apollo3. Add name to contributors list.
=> Add first wiki pages and update ACKNOWLEDGEMENTS.md

tools/artemis/artemis_svl.py
Added maximum retransmissions (64), multiple attempts (3) and better verbose/quiet formatting.
=> Svl Updates

tools/ambiq/ambiq_bin2board.py
Adds 'reset_input_buffer' just before device connection in ASB (SBL). Avoids bootloader errors when device is hammering the UART
=> Asb updates

cores/arduino/ard_sup/Arduino_defines.h, cores/arduino/ard_sup/analog/ap3_analog.cpp, cores/arduino/ard_sup/ap3_analog_types.h, libraries/Examples/examples/Example4_analogRead/Example4_analogRead.ino, variants/SparkFun_BlackBoard_Artemis/config/variant.cpp, variants/SparkFun_BlackBoard_Artemis/config/variant.h, variants/SparkFun_BlackBoard_Artemis_ATP/config/variant.cpp, variants/SparkFun_BlackBoard_Artemis_ATP/config/variant.h, variants/SparkFun_BlackBoard_Artemis_Nano/config/variant.cpp, variants/SparkFun_BlackBoard_Artemis_Nano/config/variant.h
In normal course, general pins are converted to pads. With this commit any pin number over 99 is treated as a special internal ADC channel. These 'pins' are not converted to pads via ap3_gpio_pin2pad() (calls the board variant).
ADC works correctly. The analogRead was updated as well. Internal temp is now more accurately calculated. All variants updated.
This should fix issue #45.
=> Move ADC channel selection out of variant files

libraries/EEPROM/src/EEPROM.cpp, libraries/EEPROM/src/EEPROM.h
Looks like the coversion to v2.2 SDK broke EEPROM. am_hal_flash_reprogram_ui32() is no more. 
With a little touch-up EEPROM works again. Now better! This commit removes an extra write step and records the new data to the tempArray before we record tempArray to flash.
=> Fix EEPROM to work with SDK v2.2

cores/arduino/ard_sup/ap3_gpio.h
A super simple PR, but I wanted to be sure this won't conflict with anything else.
255 = -1 in 8bit land so we should be fine assuming there is no logic testing for pin# > 0.
=> Change UNUSED def to avoid compiler errors

.gitignore, boards.txt
arduino-cli still complains about missing elf files.  However this should probably be fixed in the cli, not here.
=> Fixes for arduino-cli.

tools/artemis/artemis_svl.py
The uploader doesn't report any status until the upload is complete which becomes problematic with increasingly large sketches. This PR adds a basic progress bar to the python uploader. Test it with the PDM example (a sketch of about 51k). 
Progress bar is not shown during verbose output because the verbose setting is already pretty active with its output.
I've compiled and included a windows EXE but not a linux/mac version.
=> Add progress bar to uploader

libraries/SPI/src/SPI.cpp, libraries/SPI/src/SPI.h
Added return value to _interruptStatus. I'm not entirely confident we are returning all we should.
Here is [example](https://github.com/Seeed-Studio/Arduino_IDE_for_RePhone/blob/master/hardware/arduino/sam/libraries/SPI/SPI.cpp) returning fault mask register as well.
[Here](https://git.ccmob.net/marcel/platformio-pkg-framework-arduinosam/commit/cf28026aef2f65e2ddc5c631d2b01a144ff0a068) is one of very few example sketches I could find that actually use the __interruptsStatus() call.
Also in this PR - Small changes to SPI.h. I decided to remove warnings to SS pin definition. I've never used a pin called 'SS' and use a GPIO for CS instead. Apollo3 doesn't have hardware support for SS so I think we can expunge it. Also, changed warning on 'CLK' to 'SCK'. I see SCK more often for SPI pins and …
=> Small cleanup

libraries/SoftwareSerial/src/SoftwareSerial.h
Change SS to inherit from Stream instead of Print. There are some libraries that expect softwareSerial to have functions like find() and setTimeout(). This fixes those 'function not found' errors.
=> Change SoftwareSerial to inherit from Stream

cores/arduino/ard_sup/ard_supers/IPAddress.cpp, cores/arduino/ard_sup/ard_supers/IPAddress.h
These files are in main arduino AVR and SAMD cores. They are needed to compile the library for the SparkFun NB IOT cellular board and are probably needed for other ethernet/IP/internetty things.
=> Add standard IPAddress files

libraries/EEPROM/examples/Example2_AllFunctions/Example2_AllFunctions.ino, libraries/EEPROM/src/EEPROM.cpp, libraries/SPI/src/SPI.h
Resolves all warning and compile errors on all examples on all boards except those listed below.  Tested with test harness at: https://github.com/konkers/Arduino_Apollo3/commit/efdb5489437e18e90c24f1e9c3e11e1e5bf416ea
libraries/Examples/examples/Example2_Serial:
* SparkFun:apollo3:artemis
* SparkFun:apollo3:edge2
* SparkFun:apollo3:edge
libraries/PDM/examples/Example1_MicrophoneOutput:
* SparkFun:apollo3:edge
libraries/PDM/examples/Example2_ConfigureMic:
* SparkFun:apollo3:edge
libraries/PDM/examples/Example3_FullConfigure:
* SparkFun:apollo3:edge
libraries/Servo/examples/Example6_19servos:
* SparkFun:apollo3:amap3atp
* SparkFun:apollo3:amap3nano
* SparkFun:apollo3:artemis
* SparkFun:apollo3:edge2
* SparkFun:apollo3:edge
libraries/Servo/examples/Example7_29servos:
* …
=> Resolve warning and compile errors with examples.

tools/artemis/artemis_svl.py
Some error reporting issues that come up with getting arduino-cli working.
=> Improve artemis_svl error reporting.

libraries/RTC/keywords.txt
Simple add. Just adds a few highlighted words. I should have had these in the original contribution.
=> Add highlighting to RTC functions

libraries/EEPROM/examples/Example1_GetPut/Example1_GetPut.ino, libraries/EEPROM/examples/Example2_AllFunctions/Example2_AllFunctions.ino, libraries/EEPROM/src/EEPROM.cpp, libraries/EEPROM/src/EEPROM.h
Write speed decreased from 30ms to 19ms due to block writing instead of multi-byte writes. Works with arbitrary length variables such as char arrays.
=> EEPROM rewrite

libraries/Examples/examples/Advanced/DisplayICRevision/DisplayICRevision.ino
=> Add example to show Apollo3 IC revision

libraries/Examples/examples/Advanced/LowPower/LowPower.ino, libraries/Examples/examples/Advanced/LowPower_WithWake/LowPower_WithWake.ino, variants/SparkFun_Edge2/config/variant.cpp, variants/SparkFun_Edge2/config/variant.h
I added two examples to the Examples->Advanced directory showing how to get the Artemis into ~3uA mode. It's pretty neat. I generally used HAL methods as I thought this was the most straight forward and if folks are doing extreme low power, they're going to need to get into the HAL.
If you think there is a better location for these examples (their own top level directory? I didn't think so) please let me know.
=> Add examples demoing low power config

libraries/SoftwareSerial/src/SoftwareSerial.cpp
This PR makes software serial work reliably on pins connected to translation buffers such as the TXB0104 used on the SparkFun LTE cellular shield.
On some GPIO the g_AM_HAL_GPIO_INPUT_PULLUP seems to be strong enough to cause problems with translation buffers like the TXB0104. Limiting to the pullup to 24k fixes the issue.
With just g_AM_HAL_GPIO_INPUT_PULLUP the TXB0104 has a min voltage of 1.28V:
The Apollo3 can't interpret the 1.3V as low .
But if we use the 24k pullup g_AM_HAL_GPIO_INPUT_PULLUP_24 the signal gets much better:
And just for fun, here is pull up with 12k. The low voltage raises as the pull up resistance decreases we would expect:
This suggests the generic "g_AM_HAL_GPIO_INPUT_PULLUP" uses a strong pullup, however it's not clear in the HAL what "WEAK" means:
I don't …
=> Increase pullup resistor on RX pin

libraries/SoftwareSerial/src/SoftwareSerial.cpp
This PR fixes a bug that corrupts non-visible ASCII.
Notes:
The Pin Change Interrupt was firing after the compare interrupt (completion of byte) which was causing the incorrect start of a new byte. PCI is now cleared at the end of Compare. In the future, we could change the PCI from CHANGE to FALLING to be more sure that we're seeing the start of a new byte but it's not a guarantee. And this PR works.
This was found while connecting the Artemis to the LTE shield using software serial. Lots of \n and \r's in the AT command flows that were getting corrupt. This fixes those corruptions.
=> Clear PCI at end of byte

cores/arduino/ard_sup/Arduino_defines.h, cores/arduino/ard_sup/analog/ap3_analog.cpp, cores/arduino/ard_sup/main.cpp
@nseidle these are some changes that I had to make when getting the TFLM code to run on Edge. My concern is about the 2nd commit. Maybe one solution would be to implement a template function that could be used wherever the original macro would have been used. That way the signatures can be different (conflict is with ```min``` as used here):
```stl_algobase.h```
``` c++
template<typename _Tp, typename _Compare>
_GLIBCXX14_CONSTEXPR
inline const _Tp&
min(const _Tp& __a, const _Tp& __b, _Compare __comp)
{
//return __comp(__b, __a) ? __b : __a;
if (__comp(__b, __a))
return __b;
return __a;
}
```
=> Tensorflow micro lite compatibility

libraries/SPI/src/SPI.cpp
This decreases the byte wise transaction from 26us to 19us, a 25% improvement. It does it by moving the iomTransfer struct to global and assigning the values that don't change into the begin function.
These changes along with the SDfat changes (incoming) make for some spectacular performance:
With SPI clock freq at 48MHz we get 
write: 286 / 289 kb/s
read: 958 / 958 kb/s
On a clean format, 8GB Sandisk microSD card.
There was also a bug that allowed the core SPI freq to go above 48MHz. This PR fixes that as well.
=> Increase baseline SPI bulk transfer speeds

cores/arduino/am_sdk_ap3/mcu/apollo3/hal/am_hal_uart.c, cores/arduino/ard_sup/ap3_uart.h, cores/arduino/ard_sup/uart/ap3_uart.cpp
This PR makes Serial TX writes and prints interrupt driven rather than a blocking serial transfer one byte at a time. The _tx_buffer was there, I just implemented it. This reduces the time spent on Serial.prints significantly.
Here is example output running at 9600bps without this PR:
And here is example output with this PR:
Note the 66ms is because the TX ring buffer is 256bytes and myString is 293 so we have to wait for the UART to open up. If we increase the size of the ring buffer, this value goes to 0.
Also **availableForWrite()** method is now implemented.
Also in this PR is a patch for the HAL to make am_hal_uart_flags_get() work.
Here is my test sketch:
void setup() {
Serial.begin(9600);
delay(10);
Serial.println("Serial buffer testing");
String myString = "Lorem ipsum dolor sit …
=> Add ring buffer for serial TX

cores/arduino/ard_sup/analog/ap3_analog.cpp, cores/arduino/ard_sup/ap3_gpio.h, cores/arduino/ard_sup/gpio/ap3_gpio.cpp, docs/ACKNOWLEDGEMENTS.md
For your review, a potential fix for issue #98.
The changes add a new pinMode function that maps commonly used Arduino pin mode constants to internal methods using a pincfg structure and makes changes to existing defines to reflect this update.
Please Note:
1) In the implementation of the pinMode function I used a variable to assign the desired pin mode mapping and just called the internal function once. I did this instead of calling the function at each case (without the variable) because it seemed like it looked cleaner and may optimize better.  However this assumes the am_hal_gpio_pincfg_t structure is safe to assign to a new variable (does not use pointers, etc).  In this case the implementation is safe but future modifications could potentially break this if the = operator is not …
=> Fix for Broken Arduino libraries due to implementaion of commonly used GPIO constants, issue #98

libraries/Wire/keywords.txt, libraries/Wire/src/Wire.cpp, libraries/Wire/src/Wire.h
I've added a setPullups() function. This allows users to select between 0, 1.5k, 6k, 12k, and 24k, for the built in pull ups on the I2C lines. Because we call begin() after user selects their pull up values, I needed to store clock speed. 
I addition, I moved the iomTransfer setup of default values to the begin function. This was done for SPI as well to decrease the amount of cycles spent setting up values for every I2C transfer. It won't save as much time as the SPI change did, but it will cut it down a bit. It does increase RAM footprint by the size of iomtransfer but I'm not worried about it.
I chose to allow user to pass a uint32_t to the **setPullups()** function. If desired, we could pass the full HAL type def of am_hal_gpio_pullup_e but I think it's easier to use a bare number.
=> Allow for changing pull ups for Wire pins

cores/arduino/ard_sup/ap3_uart.h, cores/arduino/ard_sup/uart/ap3_uart.cpp
Addresses #110 while still maintaining feature improvements from #95
=> fix uart w/ better hal utilization

cores/arduino/ard_sup/analog/ap3_analog.cpp
Hi gang,
This PR allows power_adc_disable() to set ap3_adc_initialized to false, so the ADC will be reinitialized automatically by the next analogRead if required.
Enjoy!
Paul
=> Updates to ap3_adc_initialized

libraries/RTC/examples/Example3_TestRTC/Example3_TestRTC.ino, libraries/RTC/src/RTC.cpp
The HAL changed how it referenced months (from 0-11 to 1-12). 
Fix month adjustment. Add test example.
=> Fix month adjustment. Add test example.

libraries/SPI/examples/Example2_MoreSPIPorts/Example2_MoreSPIPorts.ino
Nothing fancy. Just another example to show how to configure additional ports.
=> Add example configuring alternate SPI ports.

variants/redboard_artemis_atp/config/variant.cpp, variants/redboard_artemis_atp/config/variant.h
The A32 pin definition for the Artemis ATP is missing, so I am adding it.
=> Add Artemis ATP analog pin A32 definition

platform.txt
this is a rudimentary option but it does allow the user to see the size of various output sections at compile time. the ```.data``` section corresponds (roughly) to static RAM usage.
=> Simple Solution to Add RAM Statistic at Compile

cores/arduino/ard_sup/analog/ap3_analog.cpp
=> disable adc channels while reconfiguring

cores/arduino/ard_sup/uart/ap3_uart.cpp
=> reorder uart initialization before pin configuration

tools/artemis/artemis_svl.py
This adds back serial exception printing.
It also adds a few helper texts:
Below - when COM is valid but the target fails to respond to the 'enter bootload' command.
Below - verbose output when COM is valid but target fails to respond:
=> Fix svl script

cores/arduino/ard_sup/ap3_uart.h, cores/arduino/ard_sup/uart/ap3_uart.cpp
This PR
* Increases the UART buffers from 256 * 4 (TX/RX for UART0 and UART1) to 4096 * 4
* Removes the loop within the RX ISR
* These changes allow Artemis to receive full speed 460800bps without dropping bytes
We are only doing single byte reads from the UART FIFO. By calling am_hal_uart_transfer multiple times it increases the ISR time.
Original timing:
Timing after this PR:
You can see the ISR becomes shorter and more repetitive. 
FWIW - With burst mode turned on, ISR drops even more to 8.5us so 921600bps may be possible.
For reference:
* How big is RX FIFO within HAL? 32 bytes
* Is there a 'nearly full' interrupt for the RX FIFO? No
* We could check the RX FIFO empty bit in the ISR in a loop but this is basically skirting the HAL layer. I've attempted this without much luck.
* We …
=> Increase performance of UART RX.

libraries/EEPROM/examples/Example2_AllFunctions/Example2_AllFunctions.ino, libraries/EEPROM/src/EEPROM.cpp, libraries/EEPROM/src/EEPROM.h
since the flashContent buffer is declared on the stack it may be dynamically sized the user can take advantage of this to allow for any size EEPROM up to the allocated 1 page of flash
- added 'allowedSize' member to EEPROMClass
- added setter for allowedSize 'setLength'
- adjusted 'length' to return allowedSize
- adjusted 'writeBlockToEEPROM' to use the allowedSize of the EEPROM structure when checking flash memory.
- added example usage to Example2_AllFunctions
=> add configurable EEPROM length

cores/arduino/ard_sup/ap3_analog.h
Fixes #143 but can't explain precisely why - probably compiler specification magic. Not to mention that there was an honest error in the codebase.
=> fix extern declaration of analog channel and config maps

cores/arduino/am_sdk_ap3/mcu/apollo3/hal/am_hal_pin.h, cores/arduino/ard_sup/ap3_uart_types.h, cores/arduino/ard_sup/uart/ap3_uart_structures.c, docs/ACKNOWLEDGEMENTS.md, libraries/Examples/examples/Advanced/LowPower_WithWorkAndGPIOInterrupt/LowPower_WithWorkAndGPIOInterrupt.ino
****Second opinions and testing/checking needed before merging****
I had been trying to set Serial1 to work on pads (not pins) 9 (RX) and 10 (TX), and I narrowed it down to pad 10 not functioning as TX1.   Assigning the port to other pins worked fine (test code below - uses an FTDI plugged into a separate COM port and viewed in Termite serial monitor).
I dug into the core code, found 4 omissions plus 2 typos and made (largely untested, although no compilation warnings/errors, and some basic UART combinations work ok) fixes to files:
-	ap3_uart_structures.c
-	am_hal_pin.h
-	ap3_uart_types.h
I've double checked and fixed all the assignments for UART0 and UART1 against the pin mapping Table 559 of the Apollo3 Blue datasheet, and a pull request is pending.  Couldn't quite bring myself to do …
=> Updated uart pad mapping

variants/redboard_artemis_nano/config/variant.cpp
Hi Nathan (@nseidle ) / Owen (@oclyke),
I noticed a gremlin in the pin to pad mappings for the Artemis Nano. Pads 32 and 12 were allocated twice:
https://github.com/sparkfun/Arduino_Apollo3/blob/master/variants/redboard_artemis_nano/config/variant.cpp#L43-L46
Please check if this PR is valid, because (a) I don't have a Nano and (b) surely this means the Nano Qwiic port doesn't work at the moment?
Cheers,
Paul
=> Corrected the pads for SDA2 and SCL2 on the Nano

cores/arduino/ard_sup/gpio/ap3_gpio.cpp
Add a check in digital write to see if the pin is not longer configured for GPIO, and change it back if needed.
This allows a DigitalWrite to follow an AnalogWrite, which is consistent with the behavior some user may expect.
=> Digital w after analog fix

libraries/Examples/examples/Advanced/LowPower/LowPower.ino, libraries/Examples/examples/Advanced/LowPower_WithWake/LowPower_WithWake.ino
Third time lucky?! Or maybe it is fourth?!
=> Added extra Serial prints just before the TX&RX pins are disabled

cores/arduino/ard_sup/analog/ap3_analog.cpp, cores/arduino/ard_sup/ap3_analog.h, libraries/Examples/examples/Example4_analogRead/Example4_analogRead.ino
This PR:
* Adds a getTemperature() function. If there's a better func name, let me know. I did some googling for other platforms and didn't find any clear precident.
Function is wholly based on adc_vbatt.c example from latest Ambiq SDK. Function is required (rather than a ADC read and a series of maths) because there's a HAL call that reads the on board calibration factors. It was easier to leverage their call then roll our own. 
uint32_t ui32Retval = am_hal_adc_control(g_ADCHandle, AM_HAL_ADC_REQ_TEMP_CELSIUS_GET, fVT);
getTemperature correctly pulls in user's chosen analogResolution() with a pow(2, _analogBits) calculation.
=> Add getTemperature() to support internal temp sensor

cores/arduino/ard_sup/analog/ap3_analog.cpp, cores/arduino/ard_sup/ap3_analog.h, libraries/Examples/examples/Example4_analogRead/Example4_analogRead.ino
this should have been part of #159 but I prematurely merged it
=> rename getTemperature to getInternalTemp

platform.txt
Closes #121 using the more standard Arduino method
Unfortunately this trick is poorly documented in the 3rd party hardware specification. You can see an example in the [nRF528x Mbed-OS core's platform.txt](https://github.com/arduino/ArduinoCore-nRF528x-mbedos/blob/master/platform.txt)
=> use recipe.size.regex.data to compute static memory usage

platform.txt
somehow [this commit](https://github.com/sparkfun/Arduino_Apollo3/commit/d6997accf6f4b57908aaa6f46a0200abefe8a725) was lost and this is meant to restore it
=> back to 2018 q4 major version of gcc

.github/workflows/TestCompile.yml
Hello Andy,
I thougt you may appeciate to have automated test-compile for all the libraries in the board package 😀 .
Here it is.
I had to add 20 excludes in order to compile successfully. Maybe these examples (or the according variants.h) can be modified to have these examples also compiling successfully for the board.
Or the examples may have an
```
#if defined(ARDUINO_AM_AP3_SFE_BB_ARTEMIS_NANO)
#error This example is not intended to run on the Artemin Nano board
#endif
```
But this can be done later...
This is the complete exclude list, as can be seen in the *TestCompile.yml* file
```
- arduino-boards-fqbn: SparkFun:apollo3:artemis
examples-exclude: Example4_analogRead,LowPower_WithWork,Example2_Serial,Example2_MoreSPIPorts,Example6_19servos,Example7_29servos
- arduino-boards-fqbn: …
```
=> Add test-compile

cores/arduino/ard_sup/analog/ap3_analog.cpp
Fix for issue #192 
What was happening in the original code was pin would be set correctly with an analogWrite(). When the user went to set the 2nd pin, the timer # would be the same and the code would wait for a roll over, even though the segments were different. This would never happen and we hit an infinite loop.
This PR changes it so the roll over is only checked if the user is requesting an analogWrite() to a pin who's timer *and* segment are active. If the segments don't match, don't wait for a rollover.
I've successfully tested on the 30 PWM accessible pins of an ATP. My test sketch is below.
const int numberOfPWMPins = 32;
int pwmPin[numberOfPWMPins] = {
4,  5,  6,  7,  11,
12, 13, 18, 19, 22,
23, 24, 25, 26, 27,
28, 29, 30, 31, 32, //30 is not routed on Artemis module
33, 35, 37, …
=> Fix for sequential PWM pin setting

cores/arduino/am_sdk_ap3/mcu/apollo3/hal/am_hal_uart.h, cores/arduino/ard_sup/uart/ap3_uart.cpp
This PR adds flow control support for all UARTs (0 and 1). 
It was fairly straight forward. Below is the test sketch that shows CTS properly working. I haven't devised a succinct way to test RTS (output). 
Uart SerialTest(1, 25, 12, 10, 17); //Instance, RX, TX, RTS, CTS
void setup()
{
SerialTest.begin(115200);
SerialTest.println("SerialTest online");
}
void loop()
{
SerialTest.println("Stop this text by pulling CTS(17) high");
}
=> Add flow control

cores/arduino/ard_sup/ard_supers/HardwareSerial.h
A few libraries rely on this ability. I don't see any downside to this add. Teensy and Arduino core both have this add.
=> Add Print::write to get write(buf, size)

docs/CONTRIBUTING.md
adds a short description of typical development lifecycle + branch usage
=> add development lifecycle documentation

boards.txt
=> fix 1.8.13 support

variants/SFE_ARTEMIS/variant.h, variants/SFE_ARTEMIS_ATP/variant.h, variants/SFE_ARTEMIS_DK/variant.h, variants/SFE_ARTEMIS_MM_PB/variant.h, variants/SFE_ARTEMIS_NANO/variant.h, variants/SFE_ARTEMIS_THING_PLUS/variant.h
this is a temporary patch for #271
the better fix would be for Arduino to implement an SD lib that has fall-backs that leverage the SPI api or the digital pin functions in that order
=> patch support for Arduino SD lib

cores/arduino/sdk/core-extend/AnalogInternal.h, cores/arduino/sdk/core-implement/CommonAnalog.cpp
fixes #277
actually, the getTempDegF function incorrectly returned the temperature in deg C. This changes the name of that function and adds another function to convert that value to deg F.
=> add getTempDegC

libraries/Wire/src/Wire.h
fixes #276
```Print.h``` include is part of ```Arduino.h```
=> remove Print.h include from Wire.h

.github/workflows/generate-variants.yml, platform.txt
weak functions were being squashed in the library, adding a --whole-archive flag fixes this issue, but introduces a new multiple definitions issue which i am getting around right now by adding the --allow-multiple-definition flag.
=> edit mbed library inclusion to fix weak function defs

tools/config/blocklist.json
Arduino can control its own warning settings. also removed -MMD from blocklist.
=> add warning flags to blocklist

libraries/EEPROM/examples/Example2_Structures/Example2_Structures.ino, libraries/EEPROM/src/EEPROM.cpp, libraries/EEPROM/src/EEPROM.h, platform.txt
=> Fix eeprom

libraries/Wire/src/Wire.cpp
The original default was 400kHz. I'm not sure of the root, I believe mbed imposed? But this was causing problems with a lot of libraries that assume 100kHz start. This PR reduces the bus speed to 100kHz.
Original:
After PR:
=> Reduce default I2C clock

libraries/RTC/examples/Example6_LowPower_Alarm/Example6_LowPower_Alarm.ino, libraries/RTC/keywords.txt, libraries/RTC/src/RTC.cpp, libraries/RTC/src/RTC.h, libraries/WDT/examples/Example3_WDT_LowPower/Example3_WDT_LowPower.ino
Hi @Wenn0101,
A very minor PR to correct the low-power code included in the RTC/WDT examples and add a clear interrupt function to the RTC library that I missed a long time ago.
My hope is that these changes can be included with a new artemis_svl file to make v1.2.1 compatible with macOS Big Sur.
Cheers,
Adam
=> Add improved low-power code and RTC clearInterrupt() function

libraries/PDM/src/PDM.cpp, libraries/PDM/src/PDM.h
Stopping PDM functionality may be useful to others.  In order to properly put apollo3 to sleep it is necessary to stop and re-initialize the PDM system.
=> added end method to PDM to facilitate stopping PDM
